import { NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { signIn } from "next-auth/react";
const Home: NextPage = () => {
    const { data: buscarOPData } = api.info.buscarInfoOP.useQuery({
        dni: "46756340",
        nombre: "Benjamin Vitorgan"
    });

    const { data: eventoInfo } = api.events.buscarEvento.useQuery({
        dni: "46756340",
    });

    const { mutate: crearEvento } = api.events.crearEvento.useMutation();

    console.log("userInfo", buscarOPData);
    console.log("eventInfo", eventoInfo)

    const handleEnter = async () => {
        await signIn("credentials", {
            email: "vitorganBenjamin@gmail.com",
            password: "123123123",
            name: "Benjamin Vitorgan",
            method: "signUp",
            redirect: false,
        })
    }

    const handleLogin = async () => {
        await signIn("credentials", {
            email: "vitorganBenjamin@gmail.com",
            password: "123123123",
            method: "signIn",
            redirect: false,
        })
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col justify-center gap-5">
                <button onClick={() => crearEvento({ dni: "46756340", date: "Hoy", dniPaciente: "47026765", event: "Fue al parque y paseo por 1h", type: "Hobby" })} className="border-solid border-2 border-indigo-600 w-fit">Crear evento</button>
                <button onClick={handleEnter} className="border-solid border-2 border-indigo-600 w-fit">crear cuenta</button>
                <button onClick={handleLogin} className="border-solid border-2 border-indigo-600 w-fit">login</button>
            </main>
        </>
    );
};

export default Home;
